### ISSUE TITLE
Bugs about how to find the node_sleep.node in build.

### ISSUE THREAD

**Issue by jiayaozhang** [daerduoCarey/partnet_anno_system#12]
![image](https://user-images.githubusercontent.com/38579506/107872020-2ba1e480-6eb8-11eb-9a7d-db2ca38f7eaf.png)

Dear all,

While I am compiling the code, i met some bugs, would you like to help me out?

**Comment by daerduoCarey** [comment]
Can you show us the log?

**Comment by daerduoCarey** [comment]
maybe you can try delete this line as I required but never used the sleep package. 
https://github.com/daerduoCarey/partnet_anno_system/blob/f39dab4bdaedf70ec9d117261e9839910bf3b56f/server/routes/annotation_manager.js#L9

**Comment by jiayaozhang** [comment]
Attach the log here

0 verbose cli [
0 verbose cli   '/home/chedellap/.nvm/versions/node/v15.8.0/bin/node',
0 verbose cli   '/home/chedellap/.nvm/versions/node/v15.8.0/bin/npm',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/chedellap/.nvm/versions/node/v15.8.0/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 0ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/chedellap/projects/partnet_anno_system/server/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/chedellap/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/home/chedellap/.nvm/versions/node/v15.8.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 verbose npm-session e0b3da1d4c89c583
20 timing npm:load Completed in 10ms
21 timing command:run-script Completed in 124ms
22 timing command:start Completed in 126ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/home/chedellap/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:378:20)
23 verbose stack     at maybeClose (node:internal/child_process:1067:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
24 verbose pkgid partnet_anno_system_backend@0.0.0
25 verbose cwd /home/chedellap/projects/partnet_anno_system/server
26 verbose Linux 5.4.0-65-generic
27 verbose argv "/home/chedellap/.nvm/versions/node/v15.8.0/bin/node" "/home/chedellap/.nvm/versions/node/v15.8.0/bin/npm" "start"
28 verbose node v15.8.0
29 verbose npm  v7.5.1
30 error code 1
31 error path /home/chedellap/projects/partnet_anno_system/server
32 error command failed
33 error command sh -c node ./bin/www
34 verbose exit 1

**Comment by jiayaozhang** [comment]
after  delete this line :var sleep = require('sleep'); 

I successfully see the PartNet Annotation Server.

Thanks! 

And there has one final question need your help 
What should i do to login, I login with what i have set in server.js, but it seems not work.


![image](https://user-images.githubusercontent.com/38579506/107884631-16a07200-6f07-11eb-8180-7b5ffec5fb61.png)

**Comment by jiayaozhang** [comment]
Able to create  new user.  When tried to login with the user credentials, nothing is displayed at the client (Browser) and following are the logs at server side:

![image](https://user-images.githubusercontent.com/38579506/107913841-34ef8780-6f72-11eb-98f2-c9442e7028e2.png)

**Comment by daerduoCarey** [comment]
Info from server-side looks good. what is shown on the client-side?

**Comment by jiayaozhang** [comment]
I solve this problem, thanks!

Here in what i have done

![image](https://user-images.githubusercontent.com/38579506/108038360-caab1580-704b-11eb-974c-e2cab5b04013.png)

![image](https://user-images.githubusercontent.com/38579506/108038433-df87a900-704b-11eb-90e8-33e439f1d085.png)


We should write http://localhost

I directly write **localhost,** and without add 'http://'

this is reason why it is not work.  Thanks again ! 👍
