### ISSUE TITLE
localhost didn't send any data 

### ISSUE THREAD

**Issue by ThinhPham24** [daerduoCarey/partnet_anno_system#16]
I had the problem of not being able to receive data. Please give me some advice, what should I do with this error.
![image](https://user-images.githubusercontent.com/58129562/126678927-03f9f6a2-26c3-4ac4-829f-fcaf11188569.png)
![image](https://user-images.githubusercontent.com/58129562/126679087-eacfeff3-ee55-4d6e-b6e3-1941831d8121.png)

**Comment by Mdemerdash** [comment]
Could you kindly tell me how did you solve this?

**Comment by Mdemerdash** [comment]
I solved this one by creating the database using the root and then specifying the user in server/config/server.js :
server.DB_USER = 'root'
server.DB_PASSWORD = 'root' -> if you haven't change it during installation
