### ISSUE TITLE
How to annotate our own 3D object in Annotation Workflow UI

### ISSUE THREAD

**Issue by jay-thakur** [daerduoCarey/partnet_anno_system#3]
Hi,

I have installed as per readme & setup mysql. I am able to run locally now. I want to annotate a 3D object.  Here is the steps i followed - 

<img width="955" alt="partnet_page" src="https://user-images.githubusercontent.com/2772085/76314526-fb8fb000-62fc-11ea-9a17-609fa503ac6d.png">

I selected bag & then "Annotate a New Model".  I can see part hierarchy and 'Annotation workflow'. 

But where should i keep/upload my 3D model ?

@daerduoCarey  Could you please guide/help if i am missing anything.

**Comment by JeansLli** [comment]
@jay-thakur  I think you should first make sure that there are data in /partnet_anno_system/storage/data/.  But I still face this problem after doing that. when I selected bed & then "Annotate a New Model", the annotation workflow is still blank. I can't see any 3D model here.

![Screenshot from 2020-03-23 12-45-39](https://user-images.githubusercontent.com/40200988/77282268-65985400-6d04-11ea-97e4-ac190cdcaebc.png)

Does any one know how to solve it?

**Comment by jay-thakur** [comment]
@JeansLli  I cheacked, there is 2 data models already there 'Chair' & 'Bed'.

**Comment by daerduoCarey** [comment]
Sorry for the late reply. Can you guys open the front-end browser console and the back-end nodejs console and show me the errors? I do extensive logging for both front-end and back-end.

**Comment by JeansLli** [comment]
@daerduoCarey  The only error showed in the back-end is "Error: ENOENT: no such file or directory, stat '/home/SENSETIME/lijingyi/Documents/annotation_tool/partnet_anno_system/storage/annotations/11/anno_results/0.jpg' "
![Screenshot from 2020-03-24 14-02-49](https://user-images.githubusercontent.com/40200988/77394042-5c2ceb80-6dd9-11ea-84ec-6766520c27ee.png)
![Screenshot from 2020-03-24 14-04-43](https://user-images.githubusercontent.com/40200988/77394048-60f19f80-6dd9-11ea-932b-1bc845e3c09d.png)

**Comment by JeansLli** [comment]
@daerduoCarey  But I didn't find any errors in the back-end. Could you please explain more about doing extensive logging for both front-end and back-end?
![Screenshot from 2020-03-24 14-30-53](https://user-images.githubusercontent.com/40200988/77395289-35bc7f80-6ddc-11ea-8df4-47da8f76b3e1.png)
![Screenshot from 2020-03-24 14-04-43](https://user-images.githubusercontent.com/40200988/77395371-64d2f100-6ddc-11ea-9543-411eefafea4b.png)

**Comment by jay-thakur** [comment]
@daerduoCarey  
`front-end log` - 

![image](https://user-images.githubusercontent.com/2772085/77397836-5bda2380-6dcc-11ea-8f32-da50f8751a50.png)

`backend log` -  

![image](https://user-images.githubusercontent.com/2772085/77397914-83c98700-6dcc-11ea-9c2f-1d06b46daf4d.png)

`server.js` -

```
server.HOST = 'http://localhost';
server.PORT = 3000;
server.DB_HOST = "localhost";
server.DB_USER = "root";
server.DB_PASSWORD = "root";
server.DB_NAME = "partnet_anno_system";
server.CODE_DIR = "C:/Users/jay/partnet_anno_system"

// DO NOT CHANGE!
server.DIR = server.CODE_DIR + "/storage/";
server.DATA_DIR = 'data';
server.ORI_PART_DIR = 'leaf_part_obj_normalized';
server.DOWNLOAD_DIR = 'downloads';
server.ANNO_DIR = 'annotations';
server.REMESH_PART_DIR = 'remesh_parts';
server.NEW_PART_DIR = 'new_parts';
server.ANNO_RES_DIR = 'anno_results';
server.PART_HIER_DIR = 'part_hier_templates';
server.SCREENSHOT_DIR = 'screenshots';

// set the maximum number of annotations per model
server.MAX_NUM_ANNOS_PER_MODEL = 1;
```

**Comment by jay-thakur** [comment]
Hi @JeansLli @daerduoCarey 

I fixed this. i can see Chair & Bed 3D model in 3D Interface now. 
![image](https://user-images.githubusercontent.com/2772085/77409591-841f4d80-6ddf-11ea-8e3b-b94d624ef475.png)


I was missing this TODO in `backend.js`.

```
be_config.remoteHost = 'http://localhost';
be_config.remotePort = '3000';
```

then RUN `./build.sh` again then `npm start`.

**Comment by JeansLli** [comment]
@jay-thakur Yay, you are right！ After changing the file backend.js, ./build.sh should be run AGAIN.

**Comment by daerduoCarey** [comment]
Great that you guys fixed it! Enjoy! Now closing this issue.
