### ISSUE TITLE
How to get data in the format given in Storage ?

### ISSUE THREAD

**Issue by jay-thakur** [daerduoCarey/partnet_anno_system#4]
Hi,

I have downloaded shapenet data but data is not in this format.

![image](https://user-images.githubusercontent.com/2772085/80498455-5eaad400-8989-11ea-89f3-976b7cb5c386.png)
![image](https://user-images.githubusercontent.com/2772085/80498903-e98bce80-8989-11ea-8fcd-cfbf5556b188.png)

I have installed Manifold but that also does not convert like this. 

@daerduoCarey Could you please guide/help me to do this.
@JeansLli Have you done this ?

Thanks,
Jay

**Comment by daerduoCarey** [comment]
You cannot use the ShapeNet format. :)

**Comment by jay-thakur** [comment]
@daerduoCarey How to convert it ?

**Comment by daerduoCarey** [comment]
Sorry, it's not easy and we haven't released the data. But, essentially, you need to somehow convert shapenet models into parts (having the entire model as one part is also ok). The parts used in the PartNet project are the ShapeNet meta-parts that the model designers left us with. You can refer to this paper "Learning Point Embeddings from Shape Repositories for Few-Shot Segmentation" (fig 2/sec 3) to have an understanding of the inconsistent but available parts that can be mined from ShapeNet data.

**Comment by jay-thakur** [comment]
@daerduoCarey any plan to release the code in near future ?

**Comment by daerduoCarey** [comment]
Please send an email to shapenetwebmaster@gmail.com to ask for the ShapeNet scene-graph data. I think this paper (https://mhsung.github.io/complement-me.html) provides a link "Components (877M)" that contains similar data.
