### ISSUE TITLE
Preparing my own 3d part segementation

### ISSUE THREAD

**Issue by cvjimmy0704** [daerduoCarey/partnet_anno_system#6]
Hi daerduoCarey, 
Thanks for the great work, it is a very cool tool.
When preparing my own 3d model, I ran normalize_obj.py and got "No module named geometry_utils", did I missed this file somewhere?
Thank you
Best,
Jimmy

**Comment by daerduoCarey** [comment]
please check this: https://github.com/daerduoCarey/partnet_dataset/blob/master/scripts/geometry_utils.py

**Comment by cvjimmy0704** [comment]
Thanks, it is solved. Another issue I hit after I loaded my own 3d model is that the visualization looked weird as following, I guess it will be a problem if I want to cut the model into different parts. Should I pre process  my model.
![Screen Shot 2020-07-10 at 4 44 36 PM](https://user-images.githubusercontent.com/46633391/87211936-de7de480-c2d0-11ea-9132-33dbffc2067a.png)

**Comment by Mdemerdash** [comment]
@cvjimmy0704 could you kindly tell me how did you run normalize_obj.py? in which directory did you put the geometry_utils?
